version: "3.8"
services:
  frontend:
    container_name: front_end
    build: front-end
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./front-end/
        target: /usr/src/app/

  chat_app:
    container_name: chat
    build: chat-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      SECRET: "${SECRET}"
      CLIENT: "${CLIENT}"
    volumes:
      - type: bind
        source: ./chat-app/
        target: /usr/src/app/

#  game_app:
#    container_name: game_app
#    build: gameApp

  gateway:
    container_name: gateway
    build: api-gateway/gateway
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8084:8084"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - type: bind
        source: ./api-gateway/gateway
        target: /usr/src/app/

  db:
    container_name: db
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
